### ISSUE TITLE
When validated input is in the query when called it should be stored as a parameter

### ISSUE THREAD

**Issue by RicoNijeboer** [RicoNijeboer/laravel-to-swagger#13]
```
     parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
```

https://swagger.io/docs/specification/describing-parameters/#query-parameters
