### ISSUE TITLE
Support Server Templating

### ISSUE THREAD

**Issue by RicoNijeboer** [RicoNijeboer/laravel-to-swagger#4]
https://swagger.io/docs/specification/api-host-and-base-path/

> Any part of the server URL – scheme, host name or its parts, port, subpath – can be parameterized using variables. Variables are indicated by {curly braces} in the server url, like so:
```YAML
servers:
  - url: https://{customerId}.saas-app.com:{port}/v2
    variables:
      customerId:
        default: demo
        description: Customer ID assigned by the service provider
      port:
        enum:
          - '443'
          - '8443'
        default: '443'
```
