### ISSUE TITLE
When a route is on a different domain than the default it should overwrite  the server within the path

### ISSUE THREAD

**Issue by RicoNijeboer** [RicoNijeboer/laravel-to-swagger#6]
> The global servers array can be overridden on the path level or operation level. This is handy if some endpoints use a different server or base path than the rest of the API. Common examples are:  Different base URL for file upload and download operations & Deprecated but still functional endpoints.
```
servers:
  - url: https://api.example.com/v1
paths:
  /files:
    description: File upload and download operations
    servers:
      - url: https://files.example.com
        description: Override base path for all operations with the /files path
    ...
  /ping:
    get:
      servers:
        - url: https://echo.example.com
          description: Override base path for the GET /ping operation
```

https://swagger.io/docs/specification/api-host-and-base-path/
